<a href="https://colab.research.google.com/github/manishiitg/ML_Experments/blob/master/nlp/101/count_vectorize_bag_of_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Trying out bag of words representation **

In [0]:
import spacy 
nlp = spacy.load("en_core_web_sm")

from sklearn.feature_extraction.text import CountVectorizer

In [2]:
# bag of words very simple example 

sentence = "NLP is awesome"
count_vectorizer = CountVectorizer()  
count_vectorizer.fit(sentence.split())
matrix = count_vectorizer.transform(sentence.split())
print(matrix.todense())

[[0 0 1]
 [0 1 0]
 [1 0 0]]


In [3]:
# bag of words very simple example 

sentences = ["NLP is awesome","I want to learn NLP"]
count_vectorizer = CountVectorizer()  
count_vectorizer.fit(sentences)

new_sentense = "How to learn NLP?"

matrix = count_vectorizer.transform(new_sentense.split())
print(matrix.todense())

[[0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


In [4]:

import nltk
nltk.download('punkt')

import pandas as pd
import numpy as np

from sklearn.datasets import fetch_20newsgroups

news = fetch_20newsgroups(subset="train")

print(news.keys())

df = pd.DataFrame(news['data'])
print(df.head())


count_vectorizer = CountVectorizer(
    analyzer="word", tokenizer=nltk.word_tokenize,
    preprocessor=None, stop_words='english', max_features=1000, max_df=.9)  
count_vectorizer.fit(news["data"])

# matrix = count_vectorizer.transform(new_sentense.split())
# print(matrix.todense())
print(count_vectorizer.get_feature_names())
print(count_vectorizer.vocabulary_)


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])
                                                   0
0  From: lerxst@wam.umd.edu (where's my thing)\nS...
1  From: guykuo@carson.u.washington.edu (Guy Kuo)...
2  From: twillis@ec.ecn.purdue.edu (Thomas E Will...
3  From: jgreen@amber (Joe Green)\nSubject: Re: W...
4  From: jcm@head-cfa.harvard.edu (Jonathan McDow...
['!', '#', '$', '%', '&', "'", "''", "'ax", "'d", "'ll", "'m", "'re", "'s", "'ve", '*', '**', '***', '*/', '+', '-', '-+', '--', '..', '...', '/', '/*', '/3t', '0', '0d', '0t-', '1', '1.', '1.1', '10', '100', '11', '12', '13', '14', '145', '15', '16', '17', '18', '19', '1992', '1993', '1d9', '2', '2.', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '3.1', '30', '31', '32', '33', '34', '35', '4', '40', '45', '5', '50', '6', '60', '7', '8', '80', '9', '93', ';', '<', '=', '>', '?', '[', '\\', ']', '^', '_', '_/', '`', '``', '`p', 'a.', 'a86', 'able', 'accept', 'access', 'according', 'act', '